server:
  port: 8080

spring:
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    queue: kualit-mail-service
    port: 5672
    template:
      exchange: mail-message-exchange
      ## To avoid requeue in case of fail!
    listener:
      simple:
        default-requeue-rejected: false
        ## Retry the delivery!
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5s
          multiplier: 2

  datasource:
    url: jdbc:mysql://localhost:3306/mailservice
    username:
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ****@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
